name: Build Development

on:
  workflow_dispatch: 
    inputs:
      include_iframe:
        description: 'Include iFrame'
        type: boolean
        default: false
      deployment_directory:
        description: 'Deployment Directory'
        type: string
        default: "CLIENT_NAME/BRAND/PROJECT_NAME/wip"
      build_language:
        description: 'build_language'
        type: string
        default: "en"

jobs:
  build:
    uses: scarybeasties/workflows/.github/workflows/node.build.dev.yml@main
    with:
      include_iframe: ${{ github.event.inputs.include_iframe }}
      deployment_directory: ${{ github.event.inputs.deployment_directory }}
      build_language: ${{ github.event.inputs.build_language }}
    secrets: inherit
